Feature/class interface additions
rectorphp/rector-src pull request #3368
Opened 2023-02-08 22:38 UTC by stefantalen

While working on a Rector for rector-symfony I stumbled upon some repeated logic across multiple rules.

I found some classes that might be suitable for these functions so other Rector libraries can benefit from them (Since they need rector-src). Only issue is PHPStan notices they're not being used in this project.

Any thoughts?

2023-02-11 18:17 UTC, samsonasik commented
You can add `@api` docblock above method so it will be skipped from unused method check

2023-02-13 19:29 UTC, TomasVotruba commented
Hi, actually the other direciton is preffered. The core should contain only core logic, and the framework-package should handle lower logic themselves.

Before, we had all "helper" methods in here, but they were often used only in 1 framework-package. 
The core what bloated and contained dozens of unused function. As you see, it also breaks the dead-method detection and could cause false positives we'll have to maintain.

2023-02-13 19:30 UTC, TomasVotruba requested changes
These PRs should be avoided.

2023-02-13 19:46 UTC, stefantalen commented
I see where you're coming from.

To me it feels odd to have basic PHP checks like these put away in framework specific packages, but I'll add them to rector-symfony

2023-02-13 19:46 UTC, closed without merging

2023-02-13 21:16 UTC, TomasVotruba commented
The reason we had 100 helper method for any AST change. The abstraction was so extreeme we had dozens of unused methods we had to maintain.
Sometimes the good old AST with 5 lines is much more clearer and easy to use right in the spot :)