[CleanupUnneededNullsafeOperatorRector] Wip adding new rule fix #7781
rectorphp/rector-src pull request #3400
Opened 2023-02-22 14:24 UTC by JohJohan

2023-02-22 14:26 UTC, johanadivare commented on rules/Php80/Rector/NullsafeMethodCall/CleanupUnneededNullsafeOperatorRector.php
> +        $returnNode = $this->returnStrictTypeAnalyzer->resolveMethodCallReturnNode($node->var);
This now returns `null` for all my fixtures am i doing something wrong?

2023-02-22 14:28 UTC, johanadivare commented on rules/Php80/Rector/NullsafeMethodCall/CleanupUnneededNullsafeOperatorRector.php
> +        $node = $node->var;
I now remove `->getReplace();` as well is there a way to keep that maybe i should get parent call and get it from there?

2023-02-22 14:28 UTC, ghost commented
Fixes https://github.com/rectorphp/rector/issues/7781

2023-02-22 14:28 UTC, johanadivare commented on rules/Php80/Rector/NullsafeMethodCall/CleanupUnneededNullsafeOperatorRector.php
> +        return PhpVersionFeature::NULLSAFE_OPERATOR;
Is this the way to make sure your rule only runs when we support null safe operator or should there be done something extra?

2023-02-22 14:42 UTC, samsonasik requested changes
This should go to `CodeQuality` sets

2023-02-22 15:08 UTC, johanadivare commented
@samsonasik i moved to `CodeQuality`

2023-05-06 16:25 UTC, TomasVotruba commented
This looks good :+1: Thank you for your patience, as I went trough dozens of other PRs.

Could you rebase and make the CI pass? I'll give it a priority now :slightly_smiling_face:

2023-05-06 18:20 UTC, TomasVotruba commented
@samsonasik Could you rebase and handle this one as well? It's been opened a few months, so we can handle the changes for the @johanadivare

2023-05-06 18:21 UTC, samsonasik commented
I will try 👍

2023-05-08 04:56 UTC, samsonasik commented
It has too many conflict with rebase, merge main to this branch is the way to go

2023-05-08 05:04 UTC, samsonasik commented
@JohJohan I will try continue your PR at https://github.com/rectorphp/rector-src/pull/3767

2023-05-08 10:29 UTC, closed without merging