Bugfix for issue #7900
rectorphp/rector-src pull request #3687
Opened 2023-04-25 23:25 UTC by mickeytodd

2023-04-25 23:29 UTC, samsonasik requested changes
Please add fixture test under

https://github.com/rectorphp/rector-src/tree/main/rules-tests/Privatization/Rector/Class_/ChangeReadOnlyVariableWithDefaultValueToConstantRector/Fixture

If it going to skip the change, you can copy one of fixture file with `skip_` prefix and modify

2023-04-26 04:14 UTC, samsonasik commented on rules-tests/Privatization/Rector/Class_/ChangeReadOnlyVariableWithDefaultValueToConstantRector/Fixture/skip_variable_assignment.php.inc
> +final class SkipVariableAssignment
```suggestion
final class SkipVariableArrayAppend
```

2023-04-26 04:14 UTC, samsonasik commented on rules-tests/Privatization/Rector/Class_/ChangeReadOnlyVariableWithDefaultValueToConstantRector/Fixture/skip_variable_assignment.php.inc
> +<?php
Please rename file to `skip_variable_array_append.php.inc`

2023-04-26 04:17 UTC, samsonasik requested changes
Please rename PR title to something like:

```
[Privatization]  Skip variable assign append on ChangeReadOnlyVariableWithDefaultValueToConstantRector
```

Also, could you make CI green, see error 

https://github.com/rectorphp/rector-src/actions/runs/4803271285/jobs/8547601933?pr=3687#step:5:18

2023-04-26 20:33 UTC, mickeytodd commented
@samsonasik could you please check why testing fails on Renaming/Rector/FileWithoutNamespace/PseudoNamespaceToNamespaceRector/Fixture/namespace_split.php.inc? I didn't change that file. Thanks!

2023-04-27 04:40 UTC, samsonasik commented
I am not sure, could you try rebase? If still happen, try revert your change, if still happen, it possibly due to duplicated fixture files

2023-04-27 11:52 UTC, samsonasik commented
Test failure fixed at https://github.com/rectorphp/rector-src/pull/3691, please rebase

2023-04-27 18:48 UTC, samsonasik approved these changes
Looks good, thank you 👍

2023-04-27 18:49 UTC, merged

2023-04-28 05:17 UTC, plenka commented
@mickeytodd @samsonasik Thanks for fixing this so quickly!