Add failing test fixture for ConsistentImplodeRector
rectorphp/rector-src pull request #3702
Opened 2023-04-28 14:35 UTC by nerones

# Failing Test for ConsistentImplodeRector

Based on https://getrector.com/demo/ec054f63-0f4e-489d-a3da-fa87581814f0

Reported in https://github.com/rectorphp/rector/issues/7903

2023-04-29 02:23 UTC, samsonasik requested changes
Could you try provide a patch as well, the first arg value should check its type insted of value on this line:

https://github.com/rectorphp/rector-src/blob/31f64cc2d45491304065e2f04343900110005a19/rules/CodingStyle/Rector/FuncCall/ConsistentImplodeRector.php#L98

should can be checked by something like this:

```php
$type = $this->getType($firstArgumentValue);
if ($type->isString()->yes() {
     return null;
}
```

2023-05-01 21:50 UTC, nerones commented
Thanks for making it so easy to contribute!

2023-05-01 23:50 UTC, samsonasik commented
Please update PR title to something like:

```
[CodingStyle] Skip concat on first arg on ConsistentImplodeRector
```

2023-05-01 23:52 UTC, samsonasik commented on rules-tests/CodingStyle/Rector/FuncCall/ConsistentImplodeRector/Fixture/string_arguments.php.inc
> +final class DemoFile
```suggestion
final class SkipConcatOnFirstArg
```

2023-05-01 23:53 UTC, samsonasik commented on rules-tests/CodingStyle/Rector/FuncCall/ConsistentImplodeRector/Fixture/string_arguments.php.inc
> +<?php
Please update fixture file to : `skip_concat_on_first_arg.php.inc`

2023-05-02 01:55 UTC, samsonasik approved these changes

2023-05-02 01:56 UTC, samsonasik approved these changes
Thank you @nerones

2023-05-02 01:56 UTC, merged