Cleanup CachedContainer invalidation
rectorphp/rector-src pull request #3867
Opened 2023-05-16 08:32 UTC by staabm

2023-05-16 08:34 UTC, staabm commented on src/Kernel/CacheInvalidatingContainer.php
> +            throw $e;
I though about automatically creating a fresh uncached container in this case, but it did not yet work for me.

2023-05-16 08:48 UTC, staabm commented on src/Kernel/CacheInvalidatingContainer.php
> +                'Container cache is outdated and was cleared. please re-run the command.',
lets throw with a more explicit error message, so people know about the "auto-healing" capabilities

2023-05-16 10:51 UTC, samsonasik requested changes
can "v8" container cache be named generic name or still need increase the value?

2023-05-16 11:41 UTC, staabm commented
> can "v8" container cache be named generic name or still need increase the value?

[I guess you are talking about the cache-key](https://github.com/rectorphp/rector-src/blob/c0a042c3b68eb657d7e525ae2c2648d0ec96fb19/src/Kernel/RectorKernel.php#L20). using a generic string for this cache-key does not make sense.

I think there is still [room for improvement](https://github.com/rectorphp/rector-src/pull/3867#discussion_r1194813798) but as of now, it should work as far as I know.

we need to try it for a bit longer to get an idea which cases are still problematic and which force us to increase the kernel-cache-key. if we have concrete repro steps we can think about how to progress further

2023-05-17 12:57 UTC, samsonasik approved these changes
Ok, lets merge it so we have faster feedback 👍

2023-05-17 12:57 UTC, merged

2023-05-17 14:58 UTC, samsonasik commented
@staabm I need to revert this as I tried in CodeIgniter4 project with clear-cache and got error:

```
Fatal error: Uncaught Error: Class "RectorPrefix202305\Symplify\SmartFileSystem\SmartFileSystem" not found in /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Kernel/CachedContainerBuilder.php:71
Stack trace:
#0 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Kernel/RectorKernel.php(76): Rector\Core\Kernel\CachedContainerBuilder->clearCache()
#1 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Console/Command/ProcessCommand.php(144): Rector\Core\Kernel\RectorKernel::clearCache()
```