Exclude the full docs folder from archives
rectorphp/rector-src pull request #4497
Opened 2023-07-12 23:05 UTC by stof

Refs https://github.com/rectorphp/rector/issues/7842

The issue also shows unnecessary files in the vendored evenement/evenement package. This will be solved once https://github.com/igorw/evenement/pull/82 is released and the vendored package gets updated.

2023-07-12 23:45 UTC, samsonasik requested changes, later dismissed
docs contains rector rules list overview, so at least that file rector_rules_overview.md need to be kept

https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md

2023-07-12 23:48 UTC, samsonasik commented
I see, it is about including docs in local vendor, I will let @TomasVotruba decide about it 👍

2023-07-13 07:53 UTC, stof commented
According to https://github.com/rectorphp/rector/issues/7842#issuecomment-1546656237, he seems to be OK about this change though.

2023-07-13 09:09 UTC, merged

2023-07-13 09:09 UTC, samsonasik commented
Ok, thank you @stof

2023-07-13 09:12 UTC, staabm commented
thank

2023-07-13 09:15 UTC, TomasVotruba commented
Looks good to me :+1: